#!/bin/sh

## A quick hack to deploy a generated website onto a Github repository, to be served as static content by github pages.  This is an example of a very bad shell script.

# This should only be run from the root of the gitbook project
# Replace the remote Github URL to use this on a different project

# Trigger a clean and new build
gitbook build .

# Deploy new build
# cd _book && git init && git add . && git commit -m "latest version" && git branch -m master gh-pages && git remote add practicalli-clojure git@github.com:practicalli/clojure.git && git push -f practicalli-clojure gh-pages


cd _book && git init && git add . && git commit && git push -f https://jr0cket:d729e658-0dbc-44bb-9436-9bf25694ec38@git.gitbook.com/jr0cket/clojure-practicalli.git master
